import React, { useEffect, useState } from "react";

// GitHub's classic green ramp (levels 1–4), as in sallar/github-contributions-chart.
const GREEN = ["#d6e685", "#8cc665", "#44a340", "#1e6823"];
// Blue gradient reserved for the phia work mirror. Stepped in even 14-point
// L* increments so no single shade dominates, and bottoming out at the same
// lightness as classic green so neither ramp outweighs the other.
const BLUE = ["#91ceff", "#70a1fa", "#1b7ee0", "#1559ad"];

const EMPTY = "var(--archive-empty-cell)";
const MONTHS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];

// Brackets under the calendar that explain a stretch of it. Matched on MM-DD so
// they keep working as the rolling window moves.
// The calendar is columned by week, so a range is rounded out to whole weeks —
// ending on 05-30 keeps this to May's last two columns instead of spilling into
// the week that carries May 31 into June.
const ANNOTATIONS = [{ label: "rowing national championships!", from: "05-18", to: "05-30" }];

// ponytail: a day picks one side rather than splitting the cell — blue once the
// mirror accounts for at least half of it. Split cells if mixed days matter.
function cellColor(day) {
  if (!day.level) return EMPTY;
  return (day.phia * 2 >= day.count ? BLUE : GREEN)[day.level - 1];
}

function Ramp({ colors }) {
  return (
    <span className="inline-flex gap-[3px] align-middle">
      {colors.map((color) => (
        <span
          key={color}
          className="h-[10px] w-[10px] rounded-[2px]"
          style={{ backgroundColor: color }}
        />
      ))}
    </span>
  );
}

export default function ContributionsChart() {
  const [data, setData] = useState(null);

  useEffect(() => {
    let live = true;
    // The snapshot is regenerated by `npm run contributions`; skip the browser
    // cache so a refreshed file shows up without a hard reload.
    fetch(`${import.meta.env.BASE_URL}contributions.json`, { cache: "no-cache" })
      .then((res) => (res.ok ? res.json() : Promise.reject(res.status)))
      .then((json) => live && setData(json))
      .catch(() => {}); // no snapshot yet — the section just stays hidden
    return () => {
      live = false;
    };
  }, []);

  if (!data) return null;

  const weeks = [];
  for (let i = 0; i < data.days.length; i += 7) weeks.push(data.days.slice(i, i + 7));

  // Label a column when a new month starts in it, skipping the leading partial
  // week and the last column so labels never collide.
  const monthLabels = weeks.map((week, i) => {
    if (i === 0 || i === weeks.length - 1) return null;
    const month = week[0].date.slice(5, 7);
    return weeks[i - 1][0].date.slice(5, 7) === month ? null : MONTHS[Number(month) - 1];
  });

  const brackets = ANNOTATIONS.map((note) => {
    const covered = weeks.reduce((acc, week, i) => {
      const hit = week.some((day) => day.date.slice(5) >= note.from && day.date.slice(5) <= note.to);
      return hit ? { start: acc.start ?? i, end: i } : acc;
    }, {});
    return covered.start === undefined ? null : { ...note, ...covered };
  }).filter(Boolean);

  return (
    <section aria-label="GitHub contributions">
      <h2 className="label-strong mb-3">contributions</h2>
      <div className="border-y border-border py-6">
        <div className="mb-4 flex flex-wrap items-baseline gap-4">
          <span className="specimen-index">{data.total}</span>
          <span className="label">public contributions in the last year</span>
          <span className="label ml-auto">github · {data.username}</span>
        </div>

        <div className="overflow-x-auto pb-8">
          <div className="inline-block">
            <div
              className="mb-1 grid gap-[3px]"
              style={{ gridAutoFlow: "column", gridTemplateRows: "12px" }}
            >
              {monthLabels.map((month, i) => (
                <span key={i} className="relative w-[10px]">
                  {month && <span className="label absolute left-0 top-0">{month}</span>}
                </span>
              ))}
            </div>

            <div
              className="grid gap-[3px]"
              style={{ gridAutoFlow: "column", gridTemplateRows: "repeat(7, 10px)" }}
            >
              {data.days.map((day) => (
                <span
                  key={day.date}
                  className="h-[10px] w-[10px] rounded-[2px]"
                  title={
                    `${day.count} contribution${day.count === 1 ? "" : "s"} on ${day.date}` +
                    (day.phia ? ` · ${day.phia} in ${data.repo}` : "")
                  }
                  style={{ backgroundColor: cellColor(day) }}
                />
              ))}
            </div>

            {brackets.length > 0 && (
              <div
                className="mt-1.5 grid gap-[3px]"
                style={{ gridTemplateColumns: `repeat(${weeks.length}, 10px)` }}
              >
                {brackets.map((note) => (
                  <div
                    key={note.label}
                    className="relative"
                    style={{ gridColumn: `${note.start + 1} / ${note.end + 2}` }}
                  >
                    <div className="h-1.5 border-x border-b border-border-strong" />
                    <span className="label absolute left-1/2 top-full mt-1.5 -translate-x-1/2 whitespace-nowrap text-foreground">
                      {note.label}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="mt-5 flex flex-wrap items-center gap-x-8 gap-y-3">
          <span className="label inline-flex items-center gap-2">
            <Ramp colors={GREEN} />
            personal
          </span>
          <span className="label inline-flex items-center gap-2">
            <Ramp colors={BLUE} />
            phia
          </span>
        </div>
      </div>
    </section>
  );
}
